[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--prefix=/dev/null"
[build]
  publish = "packages/website/build"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build --filter=website"
