packages:
  - "packages/example"
  - "packages/ladle"
  - "packages/ladle-react-context"
  - "packages/website"
  - "packages/playwright"
  - "e2e/addons"
  - "e2e/commonjs"
  - "e2e/config"
  - "e2e/config-ts"
  - "e2e/css"
  - "e2e/decorators"
  - "e2e/flow"
  - "e2e/programmatic"
  - "e2e/provider"
