packages:
  - 'packages/example'
  - 'packages/ladle'
  - 'packages/website'
  - 'e2e/addons'
  - 'e2e/babel'
  - 'e2e/commonjs'
  - 'e2e/config'
  - 'e2e/config-ts'
  - 'e2e/css'
  - 'e2e/decorators'
  - 'e2e/playwright'
  - 'e2e/playwright-config'
  - 'e2e/programmatic'
  - 'e2e/provider'
  - 'e2e/baseweb'
  - 'e2e/msw'
